Moji/Models/Arme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Moji.Entities
{
    public class Arme
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public int Degat { get; set; }
        public string Description { get; set; }
        public int IdClasse { get; set; }
        public Classe Classe { get; set; }
    }
}

Moji/Models/Classe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Moji.Entities
{
    //[Table("Classe")]
    public class Classe
    {
        public int Id { get; set; }

        public string Libelle { get; set; }
        public float MultiMana { get; set; }
        public float MultiSante { get; set; }
        public List<Sort> Sorts { get; set; }
        public List<Arme> Armes { get; set; }
        public List<Personnage> Personnages { get; set; }
    }
}

Moji/Models/Personnage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Moji.Entities
{
    public class Personnage
    {
        public Personnage()
        {
            this.ManaActuel = 20;
            this.ManaMax = 100;
            this.Or = 0;
            this.SanteActuel = 100;
            this.SanteMax = 100;
            this.Xp = 0;
            this.Niveau = 1;
        }

        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string AvatarUrl { get; set; }
        public float Or { get; set; }
        public float SanteActuel { get; set; }
        public float SanteMax { get; set; }
        public float ManaActuel { get; set; }
        public float ManaMax { get; set; }
        public float Xp { get; set; }
        public int Niveau { get; set; }
        public int RaceId  { get; set; }
        public Race Race { get; set; }
        public int ClasseId { get; set; }
        public Classe Classe { get; set; }

    }
}

Moji/Models/Race.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Moji.Entities
{
    public class Race
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public List<Personnage> Personnages { get; set; }

    }
}

Moji/Models/Sort.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Moji.Entities
{
    public class Sort
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public int Cout { get; set; }
        public string Description { get; set; }
        public int Degat { get; set; }
        public int IdClasse{ get; set; }
        public Classe Classe { get; set; }

    }
}

Moji/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Moji.Entities
{
    public class User
    {
        public int Id { get; set; }

        public string email { get; set; }
        public string motDePasse { get; set; }

        public List<Personnage> Personnages { get; set; }
    }
}

Moji/ViewModels/PersonnageViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Moji.ViewModels
{
    public class PersonnageViewModel 
    {
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public int RaceId { get; set; }
        public List<SelectListItem> RaceItems { get; set; }
        public int ClasseId { get; set; }
        public int Id { get; set; }

        public List<SelectListItem> ClassItems { get; set; }

    }
}

Moji/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace Moji.Controllers
{
    public class AccountController : Controller
    {
    }
}

Moji/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Moji.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
          
            return View();
        }
    }
}

Moji/Controllers/JouerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Moji.Controllers
{
    public class JouerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Moji/Controllers/PersonnageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Moji.Data;
using Moji.Entities;
using Moji.ViewModels;
using System.Linq;
using System.Net;


namespace Moji.Controllers
{

    public class PersonnageController : Microsoft.AspNetCore.Mvc.Controller
    {

        private readonly MojiDbContext db = new MojiDbContext();

        //GET : Personnage
        public IActionResult Index()
        {
            var personnages = db.Personnages.Include(x=>x.Race).Include(x=>x.Classe);

            return View(personnages);
        }

        public IActionResult Create()
        {
            var classes = db.Classes.Select(c => new SelectListItem { Text = c.Libelle, Value = c.Id.ToString() }).ToList();
            var races = db.Races.Select(c => new SelectListItem { Text = c.Libelle, Value = c.Id.ToString() }).ToList();
            return View(new PersonnageViewModel() { ClassItems=classes,RaceItems=races});
        }

        public IActionResult Save(Personnage personnage)
        {
            if (ModelState.IsValid)
            {
                if (personnage.Id.Equals(null))
                {
                    db.Add(personnage);
                }
                else
                {
                    db.Update(personnage);
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Personnage");
        }


        public IActionResult Edit(int Id)
        {
            var classes = db.Classes.Select(c => new SelectListItem { Text = c.Libelle, Value = c.Id.ToString() }).ToList();
            var races = db.Races.Select(c => new SelectListItem { Text = c.Libelle, Value = c.Id.ToString() }).ToList();
            var personnages = db.Personnages.ToList();
            PersonnageViewModel result = new PersonnageViewModel();
            foreach (Personnage perso in personnages)
            {
                if (perso.Id == Id)
                {
                    result.Id = perso.Id;
                    result.Nom = perso.Nom;
                    result.Prenom = perso.Prenom;
                    result.ClasseId = perso.ClasseId;
                    result.RaceId = perso.RaceId;
                    result.ClassItems=classes;
                    result.RaceItems = races;

                }
            }
            return View(result);
        }


        public IActionResult DeletePage(int Id)
        {
            var personnages = db.Personnages.Include(x => x.Race).Include(x => x.Classe);
            Personnage result = new Personnage();
            foreach (Personnage perso in personnages)
            {
                if (perso.Id == Id)
                {
                    result = perso;
                }
            }
            return View(result);
        }

        public IActionResult Delete(int Id)
        {
            var personnages = db.Personnages.Include(x => x.Race).Include(x => x.Classe);
            Personnage result = new Personnage();
            foreach (Personnage perso in personnages)
            {
                if (perso.Id == Id)
                {
                    result = perso;
                }
            }
            db.Remove(result);
            db.SaveChanges();
            return RedirectToAction("Index", "Personnage");
        }





        public IActionResult Details(int id)
        {
            var personnages = db.Personnages.Include(x => x.Race).Include(x => x.Classe);
            Personnage result = new Personnage();
            foreach (Personnage perso in personnages)
            {
                if (perso.Id == id)
                {
                    result = perso;
                }
            }

            return View(result);
        }

    }
}

Moji/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}


<h1>BIENVENUE</h1>

<h4>Bonjour, </h4> 
<p>
    Nous sommes ravis de vous accueillir sur notre futur jeu en ASP-NET
</p>
<p>Pour l'instant vous pouvez retrouver sur notre site les personnages</p>
<p>Une aventure extraordinaire !</p>

Moji/Views/Jouer/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<img src="~/Content/fight.gif" style="width:50%; text-align:center;" />

Moji/Views/Personnage/Create.cshtml
@model Moji.ViewModels.PersonnageViewModel

@{
    ViewData["Title"] = "Create";
}
    <div class="creerEditer">
        <h1>Créer</h1>

        <h4>Personnage</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Save">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Nom" class="control-label"></label>
                        <input asp-for="Nom" class="form-control" />
                        <span asp-validation-for="Nom" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Prenom" class="control-label"></label>
                        <input asp-for="Prenom" class="form-control" />
                        <span asp-validation-for="Prenom" class="text-danger"></span>
                    </div>
                                     
           <div class="form-group">
                        <label asp-for="RaceId" class="col-md-2 control-label">Race</label>
                        <div class="col-md-5">
                            <select asp-for="RaceId" asp-items="@Model.RaceItems" class="form-control"></select>
                            <span asp-validation-for="RaceId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="ClasseId" class="col-md-2 control-label">Classe</label>
                        <div class="col-md-5">
                            <select asp-for="ClasseId" asp-items="@Model.ClassItems" class="form-control"></select>
                            <span asp-validation-for="ClasseId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Créer" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Retour à la liste de personnage</a>
        </div>
    </div>

Moji/Views/Personnage/DeletePage.cshtml
@model Moji.Entities.Personnage

@{
    ViewData["Title"] = "DeletePage";
}

<h1>Supprimer</h1>

<h3>Etes vous sur de vouloir supprimer ce personnage ?</h3>
<div>
    <h4>Personnage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvatarUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvatarUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Or)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Or)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SanteActuel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SanteActuel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SanteMax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SanteMax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManaActuel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManaActuel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManaMax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManaMax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Xp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Xp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Niveau)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Niveau)
        </dd>
        <dt class = "col-sm-2">
            Race
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Race.Libelle) 
        </dd>
        <dt class = "col-sm-2">
            Classe
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classe.Libelle)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste des personnages</a>
    </form>
</div>

Moji/Views/Personnage/Details.cshtml
@model Moji.Entities.Personnage

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Personnage</h4>
    <hr />
    <dl class="row">
        <div class="col-4">
            <img class="imgfond affichagePersonnage" src="~/Content/fond.png" alt="" />
        </div>
        <div class="col-6 ">
            <div class="affichagePersonnageDetail">
                <p>
                    <label class="col-4">Nom : @Html.DisplayFor(model => model.Nom)</label>
                    <label class="col-4">Prénom : @Html.DisplayFor(model => model.Prenom)</label>
                    <label class="col-3">Niveau : @Html.DisplayFor(model => model.Niveau)</label>
                </p>
                <p>
                    
                    <label class="col-4">
                        Race : @Html.DisplayFor(model => model.Race.Libelle)
                    </label>
                    <label class="col-3">Classe : @Html.DisplayFor(model => model.Classe.Libelle)</label>
                </p>
                <p>
                    <label class="col-4">SanteMax : @Html.DisplayFor(model => model.SanteMax)</label>
                    <label class="col-4">ManaMax : @Html.DisplayFor(model => model.ManaMax)</label>
                </p>
                <p class="text-right">Or : @Html.DisplayFor(model => model.Or)</p>

            </div>
            <img class="mt-4" src="~/Content/image.jpg" width="80%" />
        </div>


    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editer</a> |
    <a asp-action="Index">Retour à la liste de personnage</a>
</div>

Moji/Views/Personnage/Edit.cshtml
@model Moji.ViewModels.PersonnageViewModel

@{
    ViewData["Title"] = "Edit";
}
<div class="creerEditer">
    <h1>Editer</h1>

    <h4>Personnage</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Save">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Nom" class="control-label"></label>
                    <input asp-for="Nom" class="form-control" value="@Model.Nom" />
                    <span asp-validation-for="Nom" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Prenom" class="control-label"></label>
                    <input asp-for="Prenom" class="form-control" />
                    <span asp-validation-for="Prenom" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RaceId" class="col-md-2 control-label"></label>
                    <div class="col-md-5">
                        <select asp-for="RaceId" asp-items="@Model.RaceItems" class="form-control"></select>
                        <span asp-validation-for="RaceId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="ClasseId" class="col-md-2 control-label"></label>
                    <div class="col-md-5">
                        <select asp-for="ClasseId" asp-items="@Model.ClassItems" class="form-control"></select>
                        <span asp-validation-for="ClasseId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Sauvegarder" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div>
        <a asp-action="Index">Retour sur la liste</a>
    </div>
</div>

Moji/Views/Personnage/Index.cshtml
@model IEnumerable<Moji.Entities.Personnage>

@{
    ViewData["Title"] = "Index";
}



<div class="col-12 ">
    <p>
        <div>
            <a class="creerPerso" asp-action="Create">Créer un nouveau personnage</a>
        </div>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Nom)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Prenom)
                </th>

                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Or)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.SanteMax)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ManaMax)
                </th>

                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Niveau)
                </th>
                <th>
                    Race
                </th>
                <th class="text-center">
                    Classe
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prenom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Or)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SanteMax)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ManaMax)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Niveau)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Race.Libelle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Classe.Libelle)
                    </td>
                    <td>
                            <a asp-action="Edit" class="btn btn-success mb-2 bouttonCrePerso" asp-route-id="@item.Id">Editer</a>
                            <a asp-action="Details" class="btn btn-info mb-2 bouttonCrePerso" asp-route-id="@item.Id">Details</a>
                            <a asp-action="DeletePage" class="btn btn-danger mb-2 bouttonCrePerso" asp-route-id="@item.Id">Supprimer</a>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="clear">

</div>

Moji/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="fr">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="icon" type="image/png" href="Content/logo@2x.png"/>
    <title>Moji</title>
</head>
<body>
    
    <nav>
        <div class="centrer navbarsite">
            <div class="flex-container justify-content-between">
                
                <div class="flex-container">
                    <div class="liennavbar">
                        <img class="logo" src="~/Content/logo@2x.png" />
                        <a asp-controller="Home" asp-action="Index">Accueil</a>
                        <a asp-controller="Personnage" asp-action="Index">Personnage</a>
                        <a asp-controller="Jouer" asp-action="Index">Jouer !</a>

                    </div>
                </div>
            </div>
        </div>
    </nav>

    <div class="centrer">
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>